version: '3'

services:
  mongo:
    image: mongo
    networks: 
      - assembly-net
    container_name: 'assembly-mongodb'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
    - "27017:27017"

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: 'assembly-zookeeper'
    networks: 
      - assembly-net
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: 'assembly-kafka'
    networks: 
      - assembly-net
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  kafdrop:
    image: obsidiandynamics/kafdrop:latest
    container_name: 'assembly-kafdrop'
    networks: 
      - assembly-net
    depends_on:
      - kafka
    ports:
      - 19000:9000
    environment:
      KAFKA_BROKERCONNECT: kafka:29092

  # assembly-service:
  #   container_name: assembly-service
  #   depends_on: 
  #     - mongo
  #     - zookeeper
  #     - kafka
  #   build:
  #     context: ./assembly-service/
  #   ports:
  #     - "9000:8080"
  #   networks:
  #     - assembly-net

networks: 
  assembly-net:
    driver: bridge  
