version: '3'

services:
  mongo:
    image: mongo
    container_name: 'assembly-mongodb'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
    - "27017:27017"
