spring:
  application:
    name: assembly-service
    port: 8080
  data:
    mongodb:
      uri: mongodb://root:password@${MONGO_URL:localhost}:27017/admin
      database: admin

springdoc:
  swagger-ui:
    path: /swagger-ui.html

assembly:
  default-expiration-minutes: 1
  expire-delay-milliseconds-time: 300000 # 5 min

kafka:
  bootstrap-servers: ${KAFKA_URL:localhost}:9092
  votes-topic: votes-request-topic
  consumer-group: assembly-service
  topic:
    in: votes-request-topic

client:
  customer-info:
    url: https://user-info.herokuapp.com
